export const PRODUCTS = [
  {
    id: 1, name: 'Whey Protein Gold', slug: 'whey-protein-gold',
    category: 'protein', brand: 'MuscleTech',
    price: 13999, originalPrice: 19499, discount: 27,
    rating: 4.8, reviews: 2847,
    image: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=500&q=80',
    badge: 'Best Seller',
    description: 'Premium whey protein with 25g protein per serving. Chocolate, vanilla, strawberry flavors.',
    flavors: ['Chocolate', 'Vanilla', 'Strawberry', 'Cookies & Cream'],
    sizes: ['1kg', '2kg', '5kg'],
    stock: 150,
    features: ['25g Protein/serving', 'Low Sugar', 'Fast Absorbing', 'No Fillers'],
  },
  {
    id: 2, name: 'Creatine Monohydrate', slug: 'creatine-monohydrate',
    category: 'performance', brand: 'Optimum Nutrition',
    price: 3149, originalPrice: 4549, discount: 31,
    rating: 4.9, reviews: 4521,
    image: 'https://images.unsplash.com/photo-1627483297886-49710ae1fc22?w=500&q=80',
    badge: 'Top Rated',
    description: 'Pure micronized creatine monohydrate for maximum strength and muscle gains.',
    flavors: ['Unflavored'],
    sizes: ['300g', '500g', '1kg'],
    stock: 200,
    features: ['5g per serving', 'Micronized', '99.9% Pure', 'Mixes Instantly'],
  },
  {
    id: 3, name: 'BCAA Energy Rush', slug: 'bcaa-energy-rush',
    category: 'recovery', brand: 'Dymatize',
    price: 4549, originalPrice: 6299, discount: 28,
    rating: 4.6, reviews: 1832,
    image: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=500&q=80',
    badge: 'New',
    description: 'Essential BCAAs with natural caffeine for energy and faster muscle recovery.',
    flavors: ['Watermelon', 'Blue Raspberry', 'Mango', 'Green Apple'],
    sizes: ['250g', '500g'],
    stock: 90,
    features: ['7g BCAAs', '2:1:1 Ratio', 'Natural Caffeine', 'Electrolytes'],
  },
  {
    id: 4, name: 'Pre-Workout Ignite', slug: 'pre-workout-ignite',
    category: 'pre-workout', brand: 'C4',
    price: 6649, originalPrice: 8749, discount: 24,
    rating: 4.7, reviews: 3104,
    image: 'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500&q=80',
    badge: 'Hot',
    description: 'Maximum energy, focus and pump formula for explosive workouts.',
    flavors: ['Fruit Punch', 'Cherry Limeade', 'Orange Burst', 'Blue Raspberry'],
    sizes: ['200g', '400g'],
    stock: 75,
    features: ['200mg Caffeine', 'Beta-Alanine', 'L-Citrulline', 'Niacin Flush'],
  },
  {
    id: 5, name: 'Omega-3 Fish Oil', slug: 'omega-3-fish-oil',
    category: 'health', brand: 'NOW Sports',
    price: 4199, originalPrice: 5599, discount: 25,
    rating: 4.5, reviews: 921,
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=500&q=80',
    badge: null,
    description: 'Ultra-pure Omega-3 for joint health, heart health and anti-inflammation.',
    flavors: ['Lemon', 'Unflavored'],
    sizes: ['60 caps', '120 caps', '240 caps'],
    stock: 180,
    features: ['1000mg EPA+DHA', 'Triple Strength', 'No Fishy Burps', 'Molecularly Distilled'],
  },
  {
    id: 6, name: 'Casein Night Protein', slug: 'casein-night-protein',
    category: 'protein', brand: 'MuscleBlaze',
    price: 10499, originalPrice: 13299, discount: 21,
    rating: 4.6, reviews: 1245,
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=500&q=80',
    badge: null,
    description: 'Slow-release casein protein ideal for overnight muscle recovery and growth.',
    flavors: ['Chocolate', 'Vanilla'],
    sizes: ['1kg', '2kg'],
    stock: 60,
    features: ['24g Protein', 'Slow Release', '7hr Absorption', 'Glutamine Rich'],
  },
  {
    id: 7, name: 'Mass Gainer XXL', slug: 'mass-gainer-xxl',
    category: 'gainer', brand: 'Serious Mass',
    price: 8749, originalPrice: 11549, discount: 24,
    rating: 4.4, reviews: 2187,
    image: 'https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=500&q=80',
    badge: 'Popular',
    description: '1250 calories per serving. Ultimate mass gainer for hardgainers.',
    flavors: ['Chocolate', 'Vanilla', 'Banana'],
    sizes: ['3kg', '6kg'],
    stock: 45,
    features: ['1250 Cal/serving', '50g Protein', '252g Carbs', 'Vitamins & Minerals'],
  },
  {
    id: 8, name: 'L-Glutamine Pure', slug: 'l-glutamine-pure',
    category: 'recovery', brand: 'Scitec Nutrition',
    price: 5599, originalPrice: 6999, discount: 20,
    rating: 4.5, reviews: 876,
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=500&q=80',
    badge: null,
    description: 'Pure L-Glutamine for gut health, immune support and muscle recovery.',
    flavors: ['Unflavored'],
    sizes: ['300g', '500g'],
    stock: 120,
    features: ['5g per serving', '100% Pure', 'No Additives', 'Post-Workout'],
  },
  {
    id: 9, name: 'Multivitamin Elite', slug: 'multivitamin-elite',
    category: 'health', brand: 'Animal Pak',
    price: 5249, originalPrice: 6999, discount: 25,
    rating: 4.7, reviews: 1563,
    image: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=500&q=80',
    badge: null,
    description: 'Complete vitamin and mineral formula for athletes. 30 vitamins and minerals.',
    flavors: ['N/A'],
    sizes: ['30 packs', '44 packs'],
    stock: 200,
    features: ['30+ Nutrients', 'Antioxidants', 'Digestive Enzymes', 'Energy Complex'],
  },
  {
    id: 10, name: 'Testosterone Booster', slug: 'testosterone-booster',
    category: 'performance', brand: 'TestoFuel',
    price: 12249, originalPrice: 17499, discount: 30,
    rating: 4.3, reviews: 654,
    image: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500&q=80',
    badge: 'Premium',
    description: 'Natural testosterone support with Ashwagandha, Zinc, D3 and DAA.',
    flavors: ['N/A'],
    sizes: ['120 caps'],
    stock: 80,
    features: ['KSM-66 Ashwagandha', 'D-Aspartic Acid', 'Zinc', 'Vitamin D3'],
  },
  {
    id: 11, name: 'Whey Isolate Zero', slug: 'whey-isolate-zero',
    category: 'protein', brand: 'Isopure',
    price: 19249, originalPrice: 24499, discount: 21,
    rating: 4.9, reviews: 1987,
    image: 'https://images.unsplash.com/photo-1532384748853-8f54a8f476e2?w=500&q=80',
    badge: 'Premium',
    description: '100% whey isolate with 0 fat, 0 carbs, 0 sugar. Purest protein available.',
    flavors: ['Vanilla', 'Chocolate', 'Mango', 'Unflavored'],
    sizes: ['1kg', '3kg'],
    stock: 55,
    features: ['27g Protein', '0g Fat', '0g Sugar', 'Lactose Free'],
  },
  {
    id: 12, name: 'ZMA Sleep & Recovery', slug: 'zma-sleep-recovery',
    category: 'recovery', brand: 'NOW Sports',
    price: 3499, originalPrice: 4549, discount: 23,
    rating: 4.5, reviews: 743,
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=500&q=80',
    badge: null,
    description: 'Zinc, Magnesium and B6 for deeper sleep, faster recovery and hormonal support.',
    flavors: ['N/A'],
    sizes: ['90 caps'],
    stock: 150,
    features: ['Zinc 30mg', 'Magnesium 450mg', 'Vitamin B6', 'Deep Sleep Support'],
  },
]

export const CATEGORIES = [
  { id: 'all',         label: 'All Products',  icon: '🏋️' },
  { id: 'protein',     label: 'Protein',        icon: '💪' },
  { id: 'performance', label: 'Performance',    icon: '⚡' },
  { id: 'pre-workout', label: 'Pre-Workout',    icon: '🔥' },
  { id: 'recovery',    label: 'Recovery',       icon: '🔄' },
  { id: 'gainer',      label: 'Mass Gainer',    icon: '📈' },
  { id: 'health',      label: 'Health',         icon: '❤️' },
]
